<?php
$columns = 3;
$col_width = 12 / $columns ;
?>
<div class="album py-5 bg-light">
  <div class="container">

    <div class="row">
      <div class="col">
        <h2><?=Language::GetText('videos_header')?></h2>
        <p><?=Language::GetText('viewing')?>: <?=$sub_header?></p>	
      </div>
    </div>

    <div class="row filters-categories">
      <div class="col-md-8 filter">
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link<?=($sub_header == "Most Recent") ? ' active' : ''?>" href="<?=HOST?>/browse/most-recent/"><?=Language::GetText('most_recent')?></a>
          </li>
          <li class="nav-item">
            <a class="nav-link<?=($sub_header == "Most Viewed") ? ' active' : ''?>" href="<?=HOST?>/browse/most-viewed/"><?=Language::GetText('most_viewed')?></a>
          </li>
          <li class="nav-item">
            <a class="nav-link<?=($sub_header == "Most Discussed") ? ' active' : ''?>" href="<?=HOST?>/browse/most-discussed/"><?=Language::GetText('most_discussed')?></a>
          </li>
          <li class="nav-item">
            <a class="nav-link<?=($sub_header == "Most Rated") ? ' active' : ''?>" href="<?=HOST?>/browse/most-rated/"><?=Language::GetText('most_rated')?></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Category</a>
            <div class="dropdown-menu">
              <?php foreach ($category_list as $category): ?>
              <a class="dropdown-item" href="<?=HOST?>/browse/<?=$category->slug?>/" title="<?=$category->name?>"><?=$category->name?></a>
              <?php endforeach; ?>
            </div>
          </li>
        </ul>
      </div>
    </div>

    <?php if (!empty ($browse_videos)): ?>
    <?php $video_rows = array_chunk($browse_videos, $columns); ?>

    <?php foreach ($video_rows as $videos): ?>
    <div class="row pt-4">
      <?php foreach ($videos as $video): ?>
      <div class="col-<?= $col_width ?> video">
        <div class="card mb-4 shadow-sm">
          <a href="<?=$this->getService('Video')->getUrl($video)?>/"><img alt="<?=$video->title?>" width="100%" height="225" src="<?=getVideoThumbUrl($video);?>" /></a>
          <div class="card-body">
            <p class="card-text"><strong><a href="<?=$this->getService('Video')->getUrl($video)?>/"><?=htmlspecialchars($video->title)?></a></strong>
              <small class="float-right text-muted"><?=$video->duration?></small>
              <br><?=$video->description?></p>
          </div>
        </div>
      </div>
      <?php endforeach; ?>
    </div>
    <?php endforeach; ?>

    <div class="row">
      <div class="col">
        <?=$pagination->Paginate();?>
      </div>
    </div>
    <?php else: ?>
    <div class="row alert alert-info">
      <div class="col">
        <p><?=Language::GetText('no_videos')?></p>
      </div>
    </div>
    <?php endif; ?>
</div>
