<h1><?=Language::getText('home_header')?></h1>

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Album example</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
      <p>
        <a href="#" class="btn btn-primary my-2">Main call to action</a>
        <a href="#" class="btn btn-secondary my-2">Secondary action</a>
      </p>
    </div>
  </section>

<div class="album py-5 bg-light">
    <div class="container">

      <div class="row">
          <div class="col">
            <h2>Featured Videos</h2>
           </div>
        </div>
      <div class="row">

        <?php foreach (array_slice($featured_videos, 0, 3) as $featuredVideo): ?>

        <div class="col-md-4">
             <?php $this->repeatingBlock('video.phtml', array($featuredVideo)); ?>
        </div>

        <?php endforeach; ?>

    </div>
      <div class="row">
          <div class="col">
            <h2>Popular Videos</h2>
           </div>
        </div>


    <div class="row">
        <?php foreach (array_slice($recent_videos, 0, 3) as $recent_video): ?>

        <div class="col-md-4">
             <?php $this->repeatingBlock('video.phtml', array($recent_video)); ?>
        </div>

        <?php endforeach; ?>
    </div>


      <div class="row">
          <div class="col">
            <h2>Recent Videos</h2>
           </div>
        </div>


    <div class="row">
        <?php foreach (array_slice($recent_videos, 0, 3) as $recent_video): ?>

        <div class="col-md-4">
             <?php $this->repeatingBlock('video.phtml', array($recent_video)); ?>
        </div>

        <?php endforeach; ?>
    </div>

    </div>
</div>
