<?php
$this->addMeta('videoId', $video->videoId);
$this->addMeta('theme', $this->options->themeUrl);
$this->addMeta('loggedIn', (boolean) $loggedInUser);
$this->addCss($this->options->themeUrl . '/node_modules/video.js/dist/video-js.css');
$this->addJs($this->options->themeUrl . '/node_modules/video.js/dist/video.min.js');
?>


    <div class="container">

      <div class="row pt-3">
          <div class="col header-secondary">
            <h1 class="my-3"><?php echo htmlspecialchars($video->title); ?></h1>
            <?php ( isset($message) ) ? showAlertMessage($message, $message_type) : ''; ?>
          </div>
      </div>
    
      <div class="row">
        <div class="col-md-8">
            <?php if ($video->gated && !$loggedInUser): ?>
                <div id="player-gated">
                <img width="100%" height="337" src="<?=getVideoThumbUrl($video)?>" alt="<?=htmlspecialchars($video->title);?>" />
                    <div>
                        <p><?=Language::getText('gated_video')?></p>
                        <a href="<?=HOST?>/login/?redirect=<?=urlencode($this->getService('Video')->getUrl($video))?>" class="button_small"><?=Language::getText('login')?></a>
                        <?php if ($config->enableRegistrations): ?>
                            <a href="<?=HOST?>/register/" class="button_small"><?=Language::getText('register')?></a>
                        <?php endif; ?>
                    </div>
                </div>

            <?php else: ?>
                <!-- BEGIN VIDEO -->
                <div id="player">
                    <video class="video-js" style="background-color: black;" controls preload='auto' data-setup='{ "autoplay": false }' width="100%" height="337" poster="<?=getVideoThumbUrl($video)?>">
                        <source src="<?=$config->h264Url?>/<?=$video->filename?>.mp4" type="video/mp4" />
                        <?php if ($webmEncodingEnabled): ?>
                            <source src="<?=$config->webmUrl?>/<?=$video->filename?>.webm" type="video/webm" />
                        <?php endif; ?>
                        <?php if ($theoraEncodingEnabled): ?>
                            <source src="<?=$config->theoraUrl?>/<?=$video->filename?>.ogg" type="video/ogg" />
                        <?php endif; ?>
                    </video>
                </div>
                <!-- END VIDEO -->
            <?php endif; ?>
        
           <!-- BEGIN ACTIONS -->         
           <div class="row actions">
                <div class="col-md-6">
                    <p class="large">Viewed <?=$video->views?> times.</p>
                </div>
                <div class="col-md-6">
                    <p class="text-right">
                      <a class="like rating btn btn-sm btn-outline-primary" href="" data-rating="1" data-video_id=<?=$video->videoId;?> role="button"><i class="far fa-heart like-icon" alt="Click to like this video."></i> <span class="likes badge badge-light"><?=$rating->likes?></span> <span class="sr-only"> likes for this video.</span> </a> 
                         </p>
                </div>
            </div>
            <!-- END ACTIONS -->

            <!-- BEGIN TABS -->
            <div class="row actions">
                <div class="col">
                    <nav>
                      <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <a class="nav-item nav-link active" id="nav-about-tab" data-toggle="tab" href="#nav-about" role="tab" aria-controls="nav-about" aria-selected="true"><?=Language::getText('about')?></a>
                        <a class="nav-item nav-link" id="nav-share-tab" data-toggle="tab" href="#nav-share" role="tab" aria-controls="nav-share" aria-selected="false">Embed/Share</a>
                        <a class="nav-item nav-link" id="nav-save-tab" data-toggle="tab" href="#nav-save" role="tab" aria-controls="nav-save" aria-selected="false">Save</a>
                        <a class="nav-item nav-link" id="nav-flag-tab" data-toggle="tab" href="#nav-flag" role="tab" aria-controls="nav-flag" aria-selected="false">Report</a>
                      </div>
                    </nav>
                </div>
            </div>
            <!-- END TABS -->

            <!-- BEGIN TAB CONTENT -->
            <div class="row">
                <div class="col">
                    <div class="tab-content" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-about" role="tabpanel" aria-labelledby="nav-about-tab">
                            <?php include 'blocks/watch/about.php'; ?>   
                        </div>
                        <div class="tab-pane fade show" id="nav-share" role="tabpanel" aria-labelledby="nav-share-tab">
                            <?php include 'blocks/watch/share.php'; ?>   
                        </div>
                        <div class="tab-pane fade show" id="nav-save" role="tabpanel" aria-labelledby="nav-save-tab">
                            <?php include 'blocks/watch/save.php'; ?>   
                        </div>
                        
                        <div class="tab-pane fade show" id="nav-flag" role="tabpanel" aria-labelledby="nav-flag-tab">
                            <?php include 'blocks/watch/report.php'; ?>   
                        </div>
                    </div>
                </div>
            </div>
            <!-- END TAB CONTENT -->

            <!-- BEGIN COMMENTS SECTION -->        
<?php if ($video->commentsClosed): ?>
            <div id="comments-closed" class="row">
                <div class="col alert alert-info">
                    <p class="commentMessage"><?=Language::getText('comments_closed')?></p>
                </div>
            </div>
        <?php else: ?>

            <div id="comments-form-block" class="row">
                <div id="comments" class="col">
                    <h3><?=Language::getText('comments_header')?></h3>
                    <?php include 'blocks/watch/comments_form.php'; ?>    
                </div>
            </div>
            <div id="comments-list-block" class="row">
                <div class="col">
                    <?php include 'blocks/watch/comments_list.php'; ?>    
                </div>
            </div>
 <?php endif; ?>
        </div>
            <!-- END COMMENTS SECTION -->        
        <div class="col-md-4">
            <h2>Related Content</h2>
            

        </div>
      </div>


    </div>
