<!-- FOOTER -->
  <footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>CumulusClips &middot;
  <a href="<?=HOST?>/browse/"><?=Language::GetText('videos')?></a> &middot;
  <a href="<?=HOST?>/members/"><?=Language::GetText('members')?></a> &middot;
        <?php if ($config->enableUserUploads): ?>
            <a href="<?=HOST?>/account/upload/video/"><?=Language::GetText('upload')?></a> &middot;
        <?php endif; ?>
        <a href="<?=HOST?>/contact/"><?=Language::GetText('contact')?></a> &middot;
        <a href="<?=HOST?>/video-sitemap.xml"><?=Language::GetText('sitemap')?></a></p>
  </footer>
