<?php
$video = $model;
$videoService = $this->getService('Video');
?>


        <div class="card mb-4 shadow-sm">
          <a href="<?=$videoService->getUrl($video)?>/"><img alt="<?=$video->title?>" width="100%" height="225" src="<?=$config->thumbUrl?>/<?=$video->filename?>.jpg" /></a>
            <div class="card-body">
            <p class="card-text"><strong><?=$video->title?></strong><br><?=$video->description?></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <?php $playlistId = ($loggedInUser) ? $this->getService('Playlist')->getUserSpecialPlaylist($loggedInUser, 'watch_later')->playlistId : ''; ?>
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary"data-video="<?=$video->videoId?>" data-playlist="<?=$playlistId?>"><?=Language::GetText('watch_later')?></button>
                </div>
                <small class="text-muted"><?=$video->duration?></small>
              </div>
            </div>
          </div>

