
<?php
$this->SetLayout('account');
$message_type = setMessageType($message_type);
?>

<div class="row mb-4">
    <div class="col">
    <h2><?=Language::GetText('change_password_header')?></h2>
    <p><?=Language::GetText('change_password_text')?></p>
    <?php if ($message): ?>
       <div class="message <?=$message_type?>"><?=$message?></div>
   <?php endif; ?>
    </div>
</div>
        <form action="<?=HOST?>/account/change-password/" method="post">
<div class="row">
    <div class="col-md-6">
<form>
  <div class="form-group">
    <label class="<?=(isset($errors['password']) || isset($errors['match'])) ? 'is-invalid' : ''?>" for="password"><?=Language::GetText('new_password')?></label>
    <input type="password" class="form-control" id="password" name="password" placeholder="Password">
  </div>
  <div class="form-group">
    <label class="<?=(isset($errors['confirm_password']) || isset($errors['match'])) ? 'error' : ''?>" for="confirm_password">Password</label>
    <input type="password" class="form-control" name="confirm_password" id="confirm_password" placeholder="Password">
  </div>
  <input type="hidden" name="submitted" value="TRUE">
  <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>">
  <input class="btn btn-primary" type="submit" name="button" value="<?=Language::GetText('change_password_button'    )?>" >
</form>
