<?php
$this->setLayout('account');
$message_type = setMessageType($message_type);
?>

<div class="row">
    <div class="col">
    <h2><?=Language::getText('upload_video_header')?></h2>
    <div class="message <?=$message_type?>"><?=$message?></div>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <p><?php echo Language::getText('filesize_limit'); ?>: <?php echo \Functions::formatBytes($config->videoSizeLimit, 0); ?></p>
        <p><?php echo Language::getText('upload_supported_formats') . ': ' . implode(', ', $config->acceptedVideoFormats); ?></p>

         <form action="<?php echo BASE_URL; ?>/account/upload/video/" method="post">
<div class="input-group mb-3">
<div class="custom-file">
    <input type="file" class="custom-file-input form-control" id="upload" 
            name="upload"
            data-url="<?php echo BASE_URL; ?>/ajax/upload/"
            data-text="<?php echo Language::getText('browse_files_button'); ?>"
            data-limit="<?php echo $config->videoSizeLimit; ?>"
            data-extensions="<?php echo urlencode(json_encode($config->acceptedVideoFormats)); ?>"
            data-type="video"
            data-auto-submit="true" />
    <label class="custom-file-label" for="upload">Choose file</label>
  </div>
  <div class="input-group-append">
    <button class="btn btn-outline-primary" type="submit">Upload</button>
  </div>
</div>
    <input type="hidden" name="submitted" value="true" />
    <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>" />

</form>
    </div>
</div>
