<?php 
$this->setLayout('account');

if( isset($message) ){
  $message_type = setMessageType($message, $message_type);
}

$columns = 3;
$col_width = 12 / $columns ;
$video_rows = array_chunk($userVideos, $columns);
?>

<div class="row">
  <div class="col">
    <h2><?=Language::getText('my_videos_header')?></h2>
    <div class="message <?php echo $message_type ?: ''; ?>"><?php echo $message ?: ''; ?></div>
  </div>
</div>

<?php if (count($userVideos) > 0): ?>
<?php foreach ($video_rows as $videos): ?>
<div class="row">
  <?php foreach ($videos as $video): ?>
  <div class="col-md-<?= $col_width ?>">
    <div class="card mb-4 shadow-sm">
      <?php if (isVideoPending($video->status)): ?>
           <i class="far fa-file-video" alt="<?=Language::getText($video->status)?>"></i> 
          <?php else: ?>
          <a href="<?=$this->getService('Video')->getUrl($video)?>/"><img alt="<?=$video->title?>" width="100%" height="225" src="<?=getVideoThumbnail($video);?>" /></a>
          <?php endif; ?>
            <div class="card-body">
              <p class="card-text"><strong><a href="<?=$this->getService('Video')->getUrl($video)?>/"><?=htmlspecialchars($video->title)?></a></strong>
      <?php if (!isVideoPending($video->status)): ?>
                <small class="float-right text-muted"><?=$video->duration?></small>
          <?php endif; ?>
              <br><?=$video->description?></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group btn-group-sm">

      <?php if (!isVideoPending($video->status)): ?>
                    <?php $playlistId = ($loggedInUser) ? $this->getService('Playlist')->getUserSpecialPlaylist($loggedInUser, 'watch_later')->playlistId : ''; ?>
                      <button type="button" class="btn btn-outline-secondary" data-video="<?=$video->videoId?>" data-playlist="<?=$playlistId?>"><?=Language::GetText('watch_later')?></button>
          <?php endif; ?>
          <a class="btn btn-outline-primary" href="<?=HOST?>/account/videos/edit/<?=$video->videoId?>/"><?=Language::getText('edit_video')?></a>
          <a class="btn btn-outline-danger" data-node="confirm_delete_video" href="<?=HOST?>/account/videos/<?=$video->videoId?>/"><?=Language::getText('delete_video')?></a>
                </div>
              </div>
            </div>
          </div>
  </div>
  <?php endforeach; ?>
</div>
<?php endforeach; ?>
<?=$pagination->paginate()?>
<?php else: ?>
<div class="row">
  <div class="col">
    <p><strong><?=Language::getText('no_user_videos')?></strong></p>
  </div>
</div>
<?php endif; ?>
