<!doctype html>
<html lang="<?=Language::getLocale()?>">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- CumulusClips meta tags -->
    <meta name="baseUrl" content="<?=HOST?>" />
    <meta name="themeUrl" content="<?=$this->options->themeUrl?>" />
    <?php $this->writeMeta(); ?>
    <?php Plugin::triggerEvent('theme.head'); ?>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Custom styles for this template -->
    <link href="<?=$this->options->themeUrl?>/css/default.css" rel="stylesheet">

    <link rel="shortcut icon" type="image/x-icon" href="<?=HOST?>/favicon.ico" />
    
    <!-- Ion Icons SVG Pack -->
    <script type="module" src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule="" src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons/ionicons.js"></script>

    <title><?=$meta->title?></title>
  </head>
  <body>
    <?php Plugin::triggerEvent('theme.body'); ?>

    <?php $this->block('header.phtml'); ?>

    <div class="main py-5 bg-light">
   <div class="container account">

      <div class="row pt-3">
          <div class="col">
            <h1 class="my-3">My Account</h1>
          </div>
      </div>

      <div class="row"> 
        <div class="col-md-4 account-nav">
           <?php include 'account_nav.php'; ?>
        </div>
       <div class="col-md-8">
            <?= $this->body(); ?>
        </div>
      </div>


    </div> 
    </div>

    <?php $this->block('footer.phtml'); ?>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Theme JS -->
    <script src="<?=$this->options->themeUrl?>/js/default.js"></script>
    
    <?php Plugin::triggerEvent('theme.body.bottom'); ?>
  </body>
</html>
