<!doctype html>
<html lang="<?=Language::getLocale()?>">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- CumulusClips meta tags -->
    <meta name="baseUrl" content="<?=HOST?>" />
    <meta name="themeUrl" content="<?=$this->options->themeUrl?>" />
    <?php $this->writeMeta(); ?>
    <?php Plugin::triggerEvent('theme.head'); ?>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="<?=$this->options->themeUrl?>/css/bootstrap.min.css">


    <!-- Custom styles for this template -->
    <link href="<?=$this->options->themeUrl?>/css/default.css" rel="stylesheet">

    <link rel="shortcut icon" type="image/x-icon" href="<?=HOST?>/favicon.ico" />
    
    <!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" crossorigin="anonymous">

    <title><?=$meta->title?></title>
  </head>
  <body>
    <?php Plugin::triggerEvent('theme.body'); ?>

    <?php $this->block('header.phtml'); ?>

    <div class="main py-5 bg-light">
   <div class="container account">

      <div class="row pt-3">
          <div class="col">
            <h1 class="my-3">My Account</h1>
          </div>
      </div>

      <div class="row"> 
        <div class="col-md-4 account-nav">
           <?php include 'account_nav.php'; ?>
        </div>
       <div class="col-md-8">
            <?= $this->body(); ?>
        </div>
      </div>


    </div> 
    </div>

    <?php $this->block('footer.phtml'); ?>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="<?=$this->options->themeUrl?>/js/jquery.min.js"></script>
    <script src="<?=$this->options->themeUrl?>/js/bootstrap.bundle.min.js"></script>

    <!-- Theme JS -->
    <script src="<?=$this->options->themeUrl?>/js/default.js"></script>
    
    <?php Plugin::triggerEvent('theme.body.bottom'); ?>
  </body>
</html>
