<!doctype html>
<html lang="<?=Language::getLocale()?>">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- CumulusClips meta tags -->
    <meta name="baseUrl" content="<?=HOST?>" />
    <meta name="themeUrl" content="<?=$this->options->themeUrl?>" />
    <?php $this->writeMeta(); ?>
    <?php Plugin::triggerEvent('theme.head'); ?>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="<?=$this->options->themeUrl?>/css/bootstrap.min.css">


    <!-- Custom styles for this template -->
    <link href="<?=$this->options->themeUrl?>/css/default.css" rel="stylesheet">

    <link rel="shortcut icon" type="image/x-icon" href="<?=HOST?>/favicon.ico" />
    
    <!-- Font Awesome -->
    <link href="<?=$this->options->themeUrl?>/node_modules/@fortawesome/fontawesome-free/css/all.css" rel="stylesheet">

    <title><?=$meta->title?></title>
  </head>
  <body>
    <?php Plugin::triggerEvent('theme.body'); ?>

    <?php $this->block('header.phtml'); ?>

    <div class="main bg-light">
        <?= $this->body(); ?>
    </div>

    <?php $this->block('footer.phtml'); ?>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="<?=$this->options->themeUrl?>/js/jquery.min.js"></script>
    <script src="<?=$this->options->themeUrl?>/js/bootstrap.bundle.min.js"></script>

    <!-- Clipboard JS -->
    <script src="<?=$this->options->themeUrl?>/node_modules/clipboard/dist/clipboard.min.js"></script>

    <!-- Theme-specific JS -->
    <script src="<?=$this->options->themeUrl?>/js/theme.js"></script>
    
    <?php Plugin::triggerEvent('theme.body.bottom'); ?>
  </body>
</html>
